0702/Models/TrainerTopic.cs
namespace _0702.Models
{
  public class TrainerTopic
  {
    public int Id { get; set; }
    public string TrainerId { get; set; }
    public int TopicId { get; set; }
    public ApplicationUser Trainer { get; set; }
    public Topic Topic { get; set; }
  }
}

0702/ViewModels/TrainerTopicViewModel.cs
using _0702.Models;
using System.Collections.Generic;

namespace _0702.ViewModels
{
  public class TrainerTopicViewModel
  {
    public TrainerTopic TrainerTopic { get; set; }
    public IEnumerable<ApplicationUser> Trainers { get; set; }
    public IEnumerable<Topic> Topics { get; set; }
  }
}

0702/Controllers/TrainerTopicsController.cs
using _0702.Models;
using _0702.ViewModels;
using Microsoft.AspNet.Identity;
using System.Data.Entity;
using System.Linq;
using System.Web.Mvc;

namespace _0702.Controllers
{
  public class TrainerTopicsController : Controller
  {
    private ApplicationDbContext _context;

    public TrainerTopicsController()
    {
      _context = new ApplicationDbContext();
    }
    [Authorize(Roles = "Staff, Trainer")]
    public ActionResult Index()
    {
      if (User.IsInRole("Staff"))
      {
        var trainertopics = _context.TrainerTopics.Include(t => t.Topic).Include(t => t.Trainer).ToList();
        return View(trainertopics);
      }
      if (User.IsInRole("Trainer"))
      {
        var trainerId = User.Identity.GetUserId();
        var Res = _context.TrainerTopics.Where(e => e.TrainerId == trainerId).Include(t => t.Topic).ToList();
        return View(Res);
      }
      return View("Login");
    }

    [Authorize(Roles = "Staff, Trainer")]
    public ActionResult Create()
    {
      //get trainer
      var role = (from r in _context.Roles where r.Name.Contains("Trainer") select r).FirstOrDefault();
      var users = _context.Users.Where(x => x.Roles.Select(y => y.RoleId).Contains(role.Id)).ToList();

      //get topic

      var topics = _context.Topics.ToList();

      var TrainerTopicVM = new TrainerTopicViewModel()
      {
        Topics = topics,
        Trainers = users,
        TrainerTopic = new TrainerTopic()
      };

      return View(TrainerTopicVM);
    }

    [HttpPost]
    public ActionResult Create(TrainerTopicViewModel model)
    {
      //get trainer
      var role = (from r in _context.Roles where r.Name.Contains("Trainer") select r).FirstOrDefault();
      var users = _context.Users.Where(x => x.Roles.Select(y => y.RoleId).Contains(role.Id)).ToList();

      //get topic

      var topics = _context.Topics.ToList();


      if (ModelState.IsValid)
      {
        _context.TrainerTopics.Add(model.TrainerTopic);
        _context.SaveChanges();
        return RedirectToAction("Index");
      }

      var TrainerTopicVM = new TrainerTopicViewModel()
      {
        Topics = topics,
        Trainers = users,
        TrainerTopic = new TrainerTopic()
      };

      return View(TrainerTopicVM);
    }
  }
}

0702/Views/TrainerTopics/Create.cshtml
@model _0702.ViewModels.TrainerTopicViewModel

@{
  ViewBag.Title = "Create";
}

@using (Html.BeginForm())
{
  @Html.AntiForgeryToken()
  if (Request.IsAuthenticated && User.IsInRole("Staff"))
  {
  <div class="form-horizontal">
    <h4>Assign Trainer</h4>
    <hr />
    @Html.ValidationSummary(true, "", new { @class = "text-danger" })
    <div class="form-group">
      @Html.LabelFor(model => model.TrainerTopic.TrainerId, htmlAttributes: new { @class = "control-label col-md-2" })
      <div class="col-md-10">
        @Html.DropDownListFor(x => x.TrainerTopic.TrainerId, new SelectList(Model.Trainers, "Id", "UserName"), new { @class = "form-control" })
        @Html.ValidationMessageFor(model => model.TrainerTopic.TrainerId, "", new { @class = "text-danger" })
      </div>
    </div>

    <div class="form-group">
      @Html.LabelFor(model => model.TrainerTopic.TopicId, htmlAttributes: new { @class = "control-label col-md-2" })
      <div class="col-md-10">
        @Html.DropDownListFor(x => x.TrainerTopic.TopicId, new SelectList(Model.Topics, "Id", "Name"), new { @class = "form-control" })
        @Html.ValidationMessageFor(model => model.TrainerTopic.TopicId, "", new { @class = "text-danger" })
      </div>
    </div>

    <div class="form-group">
      <div class="col-md-offset-2 col-md-10">
        <input type="submit" value="Assign" class="btn btn-default" />
      </div>
    </div>
  </div>
  }
}

0702/Views/TrainerTopics/Index.cshtml
@model IEnumerable<_0702.Models.TrainerTopic>

@{
  ViewBag.Title = "Index";
}

<h2>Index</h2>
@if (User.IsInRole("Staff"))
{
  <p>
    @Html.ActionLink("Assign Trainer To Topic", "Create")
  </p>
  using (Html.BeginForm("Index", "TrainerTopics", FormMethod.Get))
  {
    @Html.TextBox("Searching")
    <div class="form-horizontal">
      <div class="form-group">
        <div class="col-md-10">
          <input type="submit" value="Search" />
        </div>
      </div>
    </div>
  }
  <table class="table">
    <tr>
      <th>
        @Html.DisplayNameFor(model => model.Trainer)
      </th>
      <th>
        @Html.DisplayNameFor(model => model.Topic)
      </th>
      <th></th>
    </tr>

    @foreach (var item in Model)
    {
      <tr>
        <td>
          @Html.DisplayFor(modelItem => item.Trainer.UserName)
        </td>
        <td>
          @Html.DisplayFor(modelItem => item.Topic.Name)
        </td>
      </tr>
    }

  </table>
}
@if (User.IsInRole("Trainer"))
{<table class="table">
    <tr>
      <th>
        @Html.DisplayNameFor(item => item.Topic)
      </th>
      <th></th>
    </tr>
    @foreach (var item in Model)
    {
      <tr>
        <td>
          @Html.DisplayFor(modelItem => item.Topic.Name)
        </td>
      </tr>
    }
  </table>
}