0702/Controllers/CategoriesController.cs
using _0702.Models;
using System.Linq;
using System.Web.Mvc;


namespace _0702.Controllers
{
  public class CategoriesController : Controller
  {
    private readonly ApplicationDbContext _context;
    public CategoriesController()
    {
      _context = new ApplicationDbContext();
    }

    // GET: Categories
    public ActionResult Index()
    {
      return View(_context.Categories.ToList());
    }


    public ActionResult Create()
    {
      return View();
    }


    [HttpPost]
    [ValidateAntiForgeryToken]
    public ActionResult Create(Category category)
    {
      if (!ModelState.IsValid)
      {
        return View();
      }
      if (_context.Categories.Any(c => c.Name.Contains(category.Name)))
      {
        ModelState.AddModelError("Name", "Category Name is already exists.");
        return View(category);
      }
      var newcategory = new Category
      {
        Name = category.Name,
        Description = category.Description
      };
      _context.Categories.Add(newcategory);
      _context.SaveChanges();
      return RedirectToAction("Index");
    }

    [HttpGet]
    public ActionResult Edit(int id)
    {
      var cateInDb = _context.Categories.SingleOrDefault(c => c.Id == id);
      if (cateInDb == null)
      {
        return HttpNotFound();
      }
      return RedirectToAction("Index");
    }
    public ActionResult Edit(Category category)
    {
      if (!ModelState.IsValid)
      {
        return View();
      }
      if (_context.Categories.Any(c => c.Name.Contains(category.Name)))
      {
        ModelState.AddModelError("Name", "The Category Name is already exists.");
        return View(category);
      }
      var cateInDb = _context.Categories.SingleOrDefault(c => c.Id == category.Id);
      if (cateInDb == null)
      {
        return HttpNotFound();
      }
      cateInDb.Name = category.Name;
      _context.SaveChanges();
      return RedirectToAction("Index");
    }
    [HttpGet]
    public ActionResult Delete(int id)
    {
      var cateInDb = _context.Categories.SingleOrDefault(c => c.Id == id);
      if (cateInDb == null)
      {
        return HttpNotFound();
      }
      _context.Categories.Remove(cateInDb);
      _context.SaveChanges();
      return RedirectToAction("Index");
    }
  }
}

0702/Controllers/CoursesController.cs
using _0702.Models;
using _0702.ViewModels;
using System;
using System.Data.Entity;
using System.Linq;
using System.Web.Mvc;

namespace _0702.Controllers
{
  public class CoursesController : Controller
  {
    // GET: Courses
    private ApplicationDbContext _context;

    public CoursesController()
    {
      _context = new ApplicationDbContext();
    }

    // GET: Products
    [HttpGet]
    public ActionResult Index(string searchString)
    {
      var courses = _context.Courses
      .Include(c => c.Topic)
      .Include(c => c.Category);

      if (!String.IsNullOrEmpty(searchString))
      {
        courses = courses.Where(
          s => s.Name.Contains(searchString) ||
          s.Category.Name.Contains(searchString) ||
          s.Topic.Name.Contains(searchString));
      }

      return View(courses.ToList());
    }

    [HttpGet]
    //[Authorize(Roles = "admin")]
    public ActionResult Create()
    {
      var viewModel = new CourseViewModel
      {
        Categories = _context.Categories,
        Topics = _context.Topics
        .ToList()
      };
      return View(viewModel);
    }

    [HttpPost]

    public ActionResult Create(Course course)
    {
      if (!ModelState.IsValid)
      {
        return View();
      }

      if (_context.Courses.Any(c => c.Name.Contains(course.Name)))
      {
        ModelState.AddModelError("Name", "Product Name Already Exists.");
        return View();
      }

      var newCourse = new Course
      {
        Name = course.Name,
        Description = course.Description,
        CategoryId = course.CategoryId,
        TopicId = course.TopicId
      };

      _context.Courses.Add(newCourse);
      _context.SaveChanges();

      return RedirectToAction("Index");
    }

    [HttpGet]
    //[Authorize(Roles = "Staff")]

    public ActionResult Delete(int id)
    {
      var CourseInDb = _context.Courses.SingleOrDefault(c => c.Id == id);

      if (CourseInDb == null)
      {
        return HttpNotFound();
      }

      _context.Courses.Remove(CourseInDb);
      _context.SaveChanges();

      return RedirectToAction("Index");
    }

    [HttpGet]
    //[Authorize(Roles = "Staff")]

    public ActionResult Edit(int id)
    {
      var CourseInDb = _context.Courses.SingleOrDefault(c => c.Id == id);

      if (CourseInDb == null)
      {
        return HttpNotFound();
      }

      var viewModel = new CourseViewModel
      {
        Course = CourseInDb,
        Categories = _context.Categories,
        Topics = _context.Topics
        .ToList()
      };

      return View(viewModel);
    }

    [HttpPost]
    //[Authorize(Roles = "Staff")]

    public ActionResult Edit(Course course)
    {
      if (!ModelState.IsValid)
      {
        return View();
      }

      var CourseInDb = _context.Courses.SingleOrDefault(c => c.Id == course.Id);

      if (CourseInDb == null)
      {
        return HttpNotFound();
      }

      CourseInDb.Name = course.Name;
      CourseInDb.Description = course.Description;
      CourseInDb.CategoryId = course.CategoryId;
      CourseInDb.TopicId = course.TopicId;
      _context.SaveChanges();

      return RedirectToAction("Index");
    }
  }
}

0702/Controllers/TopicsController.cs
using _0702.Models;
using System.Linq;
using System.Web.Mvc;

namespace _0702.Controllers
{
  public class TopicsController : Controller
  {
    private readonly ApplicationDbContext _context;
    public TopicsController()
    {
      _context = new ApplicationDbContext();
    }

    // GET: Categories
    public ActionResult Index()
    {
      return View(_context.Topics.ToList());
    }


    public ActionResult Create()
    {
      return View();
    }


    [HttpPost]
    [ValidateAntiForgeryToken]
    public ActionResult Create(Topic topic)
    {
      if (!ModelState.IsValid)
      {
        return View();
      }
      if (_context.Topics.Any(c => c.Name.Contains(topic.Name)))
      {
        ModelState.AddModelError("Name", "Topic Name is already exists.");
        return View(topic);
      }

      _context.Topics.Add(topic);
      _context.SaveChanges();
      return RedirectToAction("Index");
    }

    [HttpGet]
    public ActionResult Edit(int id)
    {

      Topic topic = _context.Topics.Find(id);
      if (topic == null)
      {
        return HttpNotFound();
      }
      return View(topic);
    }
    public ActionResult Edit(Topic topic)
    {
      if (ModelState.IsValid)
      {
        return View();
      }
      /*if (_context.Categories.Any(c => c.Name.Contains(category.Name)))
      {
        ModelState.AddModelError("Name", "The Category Name is already exists.");
        return View(category);
      }*/
      var topicInDb = _context.Topics.SingleOrDefault(t => t.Id == topic.Id);
      if (topicInDb == null)
      {
        return HttpNotFound();
      }
      topicInDb.Name = topic.Name;
      _context.SaveChanges();
      return RedirectToAction("Index");
    }
    [HttpGet]
    public ActionResult Delete(int id)
    {
      var topicInDb = _context.Topics.SingleOrDefault(t => t.Id == id);
      if (topicInDb == null)
      {
        return HttpNotFound();
      }
      _context.Topics.Remove(topicInDb);
      _context.SaveChanges();
      return RedirectToAction("Index");
    }
  }
}

0702/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>@ViewBag.Title - FPT Education System</title>
    @Styles.Render("~/Content/css")
    @Scripts.Render("~/bundles/modernizr")

</head>
<body>
    <div class="navbar navbar-inverse navbar-fixed-top">
        <div class="container">
            <div class="navbar-header">
                <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                </button>
                @Html.ActionLink("FPT Education System", "Index", "Home", new { area = "" }, new { @class = "navbar-brand" })
            </div>
            <div class="navbar-collapse collapse">
              <ul class="nav navbar-nav">
                @if (Request.IsAuthenticated && User.IsInRole("Admin"))
                {
                  <li>@Html.ActionLink("My Account", "Index", "AccountViewModels")</li>
                  <li>@Html.ActionLink("Create a New Account", "Register", "Account")</li>                 
                }
                @if (Request.IsAuthenticated && User.IsInRole("Staff"))
                {
                  <li>@Html.ActionLink("My Account", "Index", "AccountViewModels")</li>
                  <li>@Html.ActionLink("Manage Category", "Index", "Categories")</li>
                  <li>@Html.ActionLink("Manage Topic", "Index", "Topics")</li>
                  <li>@Html.ActionLink("Manage Course", "Index", "Courses")</li>
                  <li>@Html.ActionLink("Trainee", "Index", "TraineeCourses")</li>
                  <li>@Html.ActionLink("Trainer", "Index", "TrainerTopics")</li>
                }
                @if (Request.IsAuthenticated && User.IsInRole("Trainee"))
                {
                  <li>@Html.ActionLink("My Account", "Index", "AccountViewModels")</li>
                  <li>@Html.ActionLink("Courses", "Index", "TraineeCourses")</li>
                }
                @if (Request.IsAuthenticated && User.IsInRole("Trainer"))
                {
                  <li>@Html.ActionLink("My Account", "Index", "AccountViewModels")</li>
                  <li>@Html.ActionLink("Topics", "Index", "TrainerTopics")</li>
                }
              </ul>
                @Html.Partial("_LoginPartial")
            </div>
        </div>
    </div>
    <div class="container body-content">
        @RenderBody()
        <hr />
        <footer>
          <p>&copy; @DateTime.Now.Year - FPT Education System</p>
        </footer>
    </div>

    @Scripts.Render("~/bundles/jquery")
    @Scripts.Render("~/bundles/bootstrap")
    @RenderSection("scripts", required: false)
</body>
</html>